version: '2'
services:
    nginx:
        image: registry.aliyuncs.com/syncxplus/nginx:1.11.10
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        links:
            - aries:aries
            - cancer:cancer
            - submarine:submarine
            - wecenter:wecenter
        depends_on:
            - aries
            - cancer
            - submarine
            - wecenter
    logstash:
        image: logstash:2.2.2-1
        restart: always
        volumes:
            - ./logstash:/conf
            - ./aries/logs:/logs/aries
            - ./cancer/runtime/logs:/logs/cancer
            - ./submarine/runtime/logs:/logs/submarine
        command: ["-f", "/conf/logstash.conf"]
    rabbitmq:
        image: rabbitmq:3.6.1
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        ports:
            - "5672:5672"
    aries:
        image: registry.aliyuncs.com/syncxplus/gradle:2.14.1
        restart: always
        volumes:
            - ./gradle/caches:/root/.gradle/caches
            - ./aries:/usr/bin/app
        entrypoint: /bin/bash
        command: run.sh
        links:
            - rabbitmq:rabbitmq
        depends_on:
            - rabbitmq
    cancer:
        image: registry.aliyuncs.com/syncxplus/php:7.1.3
        restart: always
        volumes:
            - ./cancer:/var/www/html
        links:
            - rabbitmq:rabbitmq
        depends_on:
            - rabbitmq
    submarine:
        image: registry.aliyuncs.com/syncxplus/php:7.1.3
        restart: always
        volumes:
            - ./submarine:/var/www/html
        links:
            - rabbitmq:rabbitmq
        depends_on:
            - rabbitmq
    wecenter:
        image: registry.aliyuncs.com/syncxplus/php:5.6.30
        restart: always
        volumes:
            - ./wecenter:/var/www/html
