version: '2'
services:
    nginx:
        image: registry.aliyuncs.com/syncxplus/nginx:1.11.10
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
        links:
            - aries:aries
            - cancer:cancer
            - submarine:submarine
            - wecenter:wecenter
        depends_on:
            - aries
            - cancer
            - submarine
            - wecenter
    aries:
        image: registry.aliyuncs.com/syncxplus/gradle:2.14.1
        restart: always
        volumes:
            - ./gradle/caches:/root/.gradle/caches
            - ./aries:/usr/bin/app
        entrypoint: /bin/bash
        command: run.sh
    cancer:
        image: registry.aliyuncs.com/syncxplus/php:7.1.3
        restart: always
        volumes:
            - ./cancer:/var/www/html
    submarine:
        image: registry.aliyuncs.com/syncxplus/php:7.1.3
        restart: always
        volumes:
            - ./submarine:/var/www/html
    wecenter:
        image: registry.aliyuncs.com/syncxplus/php:5.6.30
        restart: always
        volumes:
            - ./wecenter:/var/www/html
